name: omni-on-prem
version: '3'
services:
  omni:
    container_name: omni
    image: "ghcr.io/siderolabs/omni:${OMNI_IMG_TAG}"
    devices:
      - /dev/net/tun
    volumes:
      - etcd-data:/_out/etcd
    configs:
      - source: omni.asc
        target: /omni.asc
      - source: tls.crt
        target: /tls.crt
      - source: tls.key
        target: /tls.key
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    command: >
      --name=${OMNI_NAME}
      --account-id=${OMNI_ACCOUNT_ID}
      --cert=/tls.crt
      --key=/tls.key
      --machine-api-cert=/tls.crt
      --machine-api-key=/tls.key
      --private-key-source='file:///omni.asc'
      --bind-addr=0.0.0.0:8080
      --machine-api-bind-addr=0.0.0.0:8090
      --k8s-proxy-bind-addr=0.0.0.0:8100
      --advertised-api-url=https://${OMNI_DOMAIN}
      --advertised-kubernetes-proxy-url=https://kube.${OMNI_DOMAIN}
      --siderolink-api-advertised-url=https://api.${OMNI_DOMAIN}:443
volumes:
  etcd-data:

configs:
  omni.asc:
    content: |  
      ${ETCD_ENCRYPTION_KEY}
  tls.crt:
    content: |
      ${TLS_CERT}
  tls.key:
    content: |
      ${TLS_KEY}